---
    - name: Install OpenEMR web application packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python36.x86_64
        - python3-firewall
        - python3-pip
        - python3-cryptography
        - mariadb-server
        - mariadb
        - php-xml.x86_64
        - python3-PyMySQL.noarch
        - python3-libselinux.x86_64
        - epel-release
        - php-json.x86_64
        - python3-pexpect.noarch
        - httpd
        - php
        - php-mysqlnd
        - mod_ssl

    - name: Install the PHP mbstring by DNF
      dnf:
        name: php-mbstring
        state: latest

    - name: Provision docker configuration daemon
      template:
        src: config/httppassword
        dest: /etc/httpd/htpasswd
      notify:
        - restart apache2

    - name: Update httpd configuration safely, avoid locking yourself out
      ansible.builtin.template:
        src: config/apache2.cong.j2
        dest: /etc/httpd/conf.d/ssl.conf
        owner: root
        group: root
        mode: '0644'

    - name: check if OpenERM is installed
      stat: 
        path: /var/www/html/openemr-5_0_1_3
      register: openemr

    - name: Download and unarchive OpenERM that needs to be downloaded
      ansible.builtin.unarchive:
        src: http://172.16.204.236/openemr-5_0_1_3.tar.gz
        dest: /var/www/html/
        remote_src: yes
      when: openemr.stat.exists == False

    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0666'
      with_items:
        - /var/www/html/openemr-5_0_1_3/sites/default/sqlconf.php
        - /var/www/html/openemr-5_0_1_3/interface/modules/zend_modules/config/application.config.php
        - /var/www/html/openemr-5_0_1_3/sites/default/documents
        - /var/www/html/openemr-5_0_1_3/sites/default/edi
        - /var/www/html/openemr-5_0_1_3/sites/default/era
        - /var/www/html/openemr-5_0_1_3/sites/default/letter_templates
        - /var/www/html/openemr-5_0_1_3/gacl/admin/templates_c
        - /var/www/html/openemr-5_0_1_3/interface/main/calendar/modules/PostCalendar/pntemplates/compiled
        - /var/www/html/openemr-5_0_1_3/interface/main/calendar/modules/PostCalendar/pntemplates/cache

    - name: Ensure all services are started and enabled, docker, mariadb, http 
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - docker
        - mariadb
        - httpd

    - name: Create a new database with name 'openerm'
      community.mysql.mysql_db:
        name: openemrdb
        state: present

    - name: Create database user with name 'openerm_user' and password with openerm database privileges
      community.mysql.mysql_user:
        name: openemr_user
        password: PASSWORD
        priv: 'openemr.*:ALL'
        state: present       

    - name: Update html folder with local admin portal app
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/var/www/html/private/{{ item.split('/')[1] }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - web/index.html
        - web/style.css

    - name: Provision default html page
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ item.split('/')[1] }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - web/index.php
        - images/background.jpg
  
      notify:
       - restart apache2

    - name: Enable HTTPS access service
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled

    - name: Enable SSH access service
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled

    - name: Enable HTTP access service
      ansible.posix.firewalld:
        port: 3434/tcp
        permanent: yes
        state: enabled

    - name: Enable Docker daemon service
      ansible.posix.firewalld:
        port: 5555/tcp
        permanent: yes
        state: enabled